### ISSUE TITLE
Create README

### ISSUE THREAD

**Issue by JeremyGreig** [KelvinC181/JJK_CI-Hackathon-1#1]
As a developer
I would like to see the README
so that I can understand the project process

**Acceptance Criteria:**

- [ ] README.md file created
- [ ] README.md file signed off

**Task**

- [x] Add in the different sections for the README 
- [ ] AI Reflections
- [ ] Design choices (colour palette)
- [ ] Role responsibilties
- [ ] Bugs
- [x] Wireframes
- [ ] Responsive Screenshots
- [ ] Bugs
- [ ] Future features
- [x] User stories
