### ISSUE TITLE
Create introduction section

### ISSUE THREAD

**Issue by JeremyGreig** [KelvinC181/JJK_CI-Hackathon-1#11]
As a user
I would like to understand the rules
So that I can play the game

**Acceptance Criteria:**

- [ ] Hero image
- [ ] Introduction
- [ ] How to play
- [ ] Optional - Extra images

**Task**

- [ ] Create and add hero image
- [ ] Create introduction
- [ ] Write and add how to play section that can be opened or closed
- [ ] Optional - Extra images
