### ISSUE TITLE
Create play button

### ISSUE THREAD

**Issue by JeremyGreig** [KelvinC181/JJK_CI-Hackathon-1#12]
As a user
I would like to start the game
So my life has meaning

**Acceptance Criteria:**

- [x] Play button should start the game
- [x] Responsive
- [x] Stays on the same page
- [x] Page should change to display the game

**Task**

- [x] Create a function
