### ISSUE TITLE
Create footer

### ISSUE THREAD

**Issue by JeremyGreig** [KelvinC181/JJK_CI-Hackathon-1#13]
As a user
I would like to see external resources in the footer
So they don't distract from the main content

**Acceptance Criteria:**

- [x] Create footer
- [x] Disclaimer
- [x] Copyright
- [x] Contact Us

**Task**

- [x] Create footer in html/css/bootstrap
- [x] Create and add disclaimer text
- [x] Add in copyright to protect our millions
- [x] Add in 'Contact Us' for lonely people to use
