### ISSUE TITLE
Create input function

### ISSUE THREAD

**Issue by JeremyGreig** [KelvinC181/JJK_CI-Hackathon-1#14]
As a user
I would like to enter my number
So that I can submit it

**Acceptance Criteria:**

- [ ] Input box
- [ ] Submit function
- [ ] Valid number is between 0 and 10
- [ ] Error message if < 1 or >9 or NaN

**Task**

- [ ] Create input box in html
- [ ] Create submit function in JS
