### ISSUE TITLE
Create reset button

### ISSUE THREAD

**Issue by JeremyGreig** [KelvinC181/JJK_CI-Hackathon-1#15]
As a user
I would like to be able to reset the game
So I can start again at any time

**Acceptance Criteria:**

- [x] Reset button
- [x] Clears the current game data
- [x] Keeps on the same screen (input page) but clears the data

**Task**

- [x] Create reset button
- [x] Function to clear data and return game to phase 1
