### ISSUE TITLE
Create current total and turns display

### ISSUE THREAD

**Issue by JeremyGreig** [KelvinC181/JJK_CI-Hackathon-1#16]
As a a user
I would like to see current game situation
So that I can make my next move effectively

**Acceptance Criteria:**

- [x] Current total to be displayed
- [x] Number of turns remaining to be displayed

**Task**

- [x] Create current total box
- [x] Create turns box
- [x] Create currentTotal function 
- [x] Create turns function
