### ISSUE TITLE
Create myRoll display

### ISSUE THREAD

**Issue by JeremyGreig** [KelvinC181/JJK_CI-Hackathon-1#17]
As a user
I would like to see what my roll was
so I can choose whether to add or subtract

**Acceptance Criteria:**

- [x] User's roll needs to be calculated
- [x] Outcome needs to be displayed
- [x] Number is returned as a variable

**Task**

- [x] Create myRoll box
- [x] Create myRoll function
