### ISSUE TITLE
Create add and subtract functions

### ISSUE THREAD

**Issue by JeremyGreig** [KelvinC181/JJK_CI-Hackathon-1#18]
As a user
I would like to select my calculation input
so I can add or subtract myRoll to the currentTotal

**Acceptance Criteria:**

- [x] Addition button
- [x] Addition function
- [x] Subtraction button
- [x] Subtract function
- [x] Returns to input on submit
- [x] Correctly calculates the sum chosen

**Task**

- [x] Create an add button
- [x] Create an add function
- [x] Create a subtract button
- [x] Create a subtract function
