### ISSUE TITLE
Create success/lose message

### ISSUE THREAD

**Issue by JeremyGreig** [KelvinC181/JJK_CI-Hackathon-1#19]
As a user
I would like to know if I have won or lost
so the game can end

**Acceptance Criteria:**

- [x] Check for win/lose
- [x] Success modal
- [x] Failure modal
- [x] New game option

**Task**

- [x] Create function that when you hit 21 triggers success modal
- [x] Function that when you hit 0 triggers failure message
