### ISSUE TITLE
Create HTML/CSS/JS file structure

### ISSUE THREAD

**Issue by JeremyGreig** [KelvinC181/JJK_CI-Hackathon-1#2]
As a developer
I would like to create a base file structure
So that I can build the rest of the page within it

**Acceptance Criteria:**

- [x] Page loads without any errors
- [x] Unified CSS style across page
- [x] Passes validators
![Image](https://github.com/user-attachments/assets/38e6e7e4-0c49-420e-858c-b7bfa610edd6)
![Image](https://github.com/user-attachments/assets/1043be01-0e5a-495b-8f88-b75cdeaa5300)
![Image](https://github.com/user-attachments/assets/1f1afa7b-b475-4773-9316-02a8c68931d5)
- [x] HTML file
- [x] CSS file
- [x] JS file

**Task**

- [x] Create index.html
- [x] Create style.css
- [x] Create JS file
- [x] Validate code
- [x] Commit code
