### ISSUE TITLE
Add myRoll images

### ISSUE THREAD

**Issue by JeremyGreig** [KelvinC181/JJK_CI-Hackathon-1#20]
As a user
I would like myRoll to be displayed visually
So that it is thematically relevant

**Acceptance Criteria:**

- [ ] myRoll displayed
- [ ] Calculated correctly

**Task**

- [ ] Make/find images to support this
- [ ] Amend the code to include
- [ ] Add images to file structure
