### ISSUE TITLE
Create project board

### ISSUE THREAD

**Issue by JeremyGreig** [KelvinC181/JJK_CI-Hackathon-1#3]
As a developer
I would like to track outstanding work
so that we can deliver working software within the deadline

**Acceptance Criteria:**

- [ ] Board created in repository project in Github
- [ ] Labels added
- [ ] Column created for Backlog
- [ ] Templates in place for User Stories

**Task**

- [ ] Create board
- [ ] Create templates
- [ ] Add labels for MSC
