### ISSUE TITLE
Add difficulty modes

### ISSUE THREAD

**Issue by JeremyGreig** [KelvinC181/JJK_CI-Hackathon-1#31]
As a user
I would like to increase the game difficulty
So that I can continue to challenge myself and develop

**Acceptance Criteria:**

- [ ] Limit how many times you can use each number
- [ ] Create visual feedback for the user
- [ ] Additional fail conditions for going above or below certain totals 

**Task**

- [ ] Create function that tracks how many times a number has been used
- [ ] Create html table to display to the user
- [ ] Function for new failure states
- [ ] Create error messages for failure states
