### ISSUE TITLE
Add multiplayer

### ISSUE THREAD

**Issue by JeremyGreig** [KelvinC181/JJK_CI-Hackathon-1#33]
As a user
I would like to play with someone else
So that we can learn together

**Acceptance Criteria:**

- [ ] A second player option
- [ ] Game logic so that a player can win based on number of turns used

**Task**

- [ ] Create second player function
- [ ] Visual selection buttons
- [ ] New winner / loser trigger states
- [ ] Tracker for head-to-head record during current session
