### ISSUE TITLE
Add multiplication and division

### ISSUE THREAD

**Issue by JeremyGreig** [KelvinC181/JJK_CI-Hackathon-1#34]
As a user
I would like to have multiplication and division
So that I can challenge myself further into Key Stage 2 arithmetic maths

**Acceptance Criteria:**

- [ ] Multiplication option
- [ ] Division option
- [ ] Visual indicators

**Task**

- [ ] Create multiplication function
- [ ] Create division function
- [ ] Create buttons for each
- [ ] Test functionality
- [ ] Regression test previous functionality
