### ISSUE TITLE
MVP Testing ticket

### ISSUE THREAD

**Issue by JeremyGreig** [KelvinC181/JJK_CI-Hackathon-1#42]
As a user
I would like the deployed features to function as expected
so that I can play based on the guidelines

**Acceptance Criteria:**

- [ ] Home page to load
- [ ] Navigation links function correctly
- [ ] How to play text displayed
- [ ] See more expands further text explanation
- [ ] Play button begins the game
- [ ] Error message appears for numbers less than 1 and greater than 10
- [ ] Add button adds to total correctly
- [ ] Subtract button takes away from total correctly
- [ ] Reset button puts the game back to the start state
- [ ] Current total updates correctly through the game
- [ ] Turns number decreases with each turn
- [ ] Game winning message appears when user reaches 21
- [ ] Game loss state appears when user uses all 20 turns

**Task**

- [ ] Run above ACs as test cases
