### ISSUE TITLE
Add label to number submission box

### ISSUE THREAD

**Issue by JeremyGreig** [KelvinC181/JJK_CI-Hackathon-1#43]
As a user
I would like to have the submit box labelled
so I can easily see where I enter my number

**Acceptance Criteria:**

- [x] Text added as label to the submit button
- [x] Text should say "Enter number here"

**Task**

- [x] Add text label
