### ISSUE TITLE
Instruction modal

### ISSUE THREAD

**Issue by KelvinC181** [KelvinC181/JJK_CI-Hackathon-1#44]
As a User
I would like to see instructions to the game accessible anytime
so I could be reminded of how to play the game without losing progress

**Acceptance Criteria:**

- [ ] create instruction modal
- [ ] make sure modal can be accessed anywhere on the page

**Task**

- [ ] create instruction modal
- [ ] create function to bring the modal up with clickable link in navbar
