### ISSUE TITLE
Deployed Site Testing Ticket

### ISSUE THREAD

**Issue by KelvinC181** [KelvinC181/JJK_CI-Hackathon-1#48]
As a user
I would like the deployed features to function as expected
so that I can play based on the guidelines

**Acceptance Criteria:**

- [x] Home page to load
- [x] Navigation links function correctly
- [x] How to play text displayed
- [x] See more expands further text explanation
- [x] Play button begins the game
- [x] Error message appears for numbers less than 1 and greater than 10
- [x] Add button adds to total correctly
- [x] Subtract button takes away from total correctly
- [x] Reset button puts the game back to the start state
- [x] Current total updates correctly through the game
- [x] Turns number decreases with each turn
- [x] Game winning message appears when user reaches 21
- [x] Game loss state appears when user uses all 20 turns
- [x] Win/Lose modal buttons functionality 
- [x] Responsive test shows all responsive views
- [x] HTML Validator
- [x] CSS Validator
- [x] JS Validator
- [x] Lighthouse Testing

**Task**

- [x] Run above ACs as test cases

**Comment by JeremyGreig** [comment]
![Image](https://github.com/user-attachments/assets/75e1387e-0419-405f-ba67-22b5d6be6ba1)

![Image](https://github.com/user-attachments/assets/ba9a8bf4-4e3e-4181-a060-eecc6415f1ef)

![Image](https://github.com/user-attachments/assets/989b1471-1d68-43cc-a1a9-6d8d9a78bcc8)

![Image](https://github.com/user-attachments/assets/accc7ae2-b20c-45b6-af49-891612faa834)

![Image](https://github.com/user-attachments/assets/9e3cc808-0248-483c-bfff-ecaf4aee4b7b)

![Image](https://github.com/user-attachments/assets/6684e539-c55c-47f8-8575-9b69f7e7b1c4)

![Image](https://github.com/user-attachments/assets/1fdd456a-4df7-4cf5-a474-77f7d7810001)

![Image](https://github.com/user-attachments/assets/41dd617d-b06c-4940-b74d-ca5b47a901ac)

**Comment by JeremyGreig** [comment]
![Image](https://github.com/user-attachments/assets/09ded653-b658-4fe2-93b3-8bcc8074ae54)

![Image](https://github.com/user-attachments/assets/af9bc640-5d32-4e0b-8fea-0e20bb97d33d)

![Image](https://github.com/user-attachments/assets/73c8cf89-c7dd-4452-a343-48c965c30fc7)
