### ISSUE TITLE
Add disclaimer to footer

### ISSUE THREAD

**Issue by JeremyGreig** [KelvinC181/JJK_CI-Hackathon-1#5]
As a user
I would like to understand risks of gambling
So I don't sue the website incorrectly when I lose everything

**Acceptance Criteria:**

- [x] Disclaimer within the footer

Optional:
- [ ] Links to gambling support website

**Task**

- [x] HTML and CSS
