### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by JeremyGreig** [KelvinC181/JJK_CI-Hackathon-1#6]
As a user
I would like the website to be responsive
So I can access it on all devices

**Acceptance Criteria:**

- [x] Works on small devices (add in width)
- [x] Works on medium devices
- [x] Works on larger devices

**Task**

- [x] Add widths to above ACS
- [x] Create the CSS code
- [x] Use bootstrap classes and media queries
