### ISSUE TITLE
Semantic design

### ISSUE THREAD

**Issue by JeremyGreig** [KelvinC181/JJK_CI-Hackathon-1#7]
As a screen reader
I would like to accurately reflect the page
so those with visual impairments can navigate

**Acceptance Criteria:**

- [x] Code passes validator checks
- [x] Code passes review checks

**Task**

- [x] Semantic and stuff innit
