### ISSUE TITLE
Add theme selection

### ISSUE THREAD

**Issue by JeremyGreig** [KelvinC181/JJK_CI-Hackathon-1#8]
As a secondary user
I would like to set the game to other themes
So it can feel more relevant to me

**Acceptance Criteria:**

- [ ] Poker theme
- [ ] Drinking game theme
- [ ] Other themes TBC

**Task**

- [ ] Begin ideation if time allows
- [ ] Use JS to allow user to select game theme on page load
